image:
  file: .gitpod.Dockerfile
  
tasks:
  - before: echo "export GRAALVM_HOME=~/.sdkman/candidates/java/20.1.0.r11-grl/" >> .profile && source .profile && ${GRAALVM_HOME}/bin/gu install native-image
    init: ./mvnw package -Pnative
